### ISSUE TITLE
restore clipboard data 

### ISSUE THREAD

**Issue by Alex-CodeLab** [Alex-CodeLab/passwordmanager#18]
_Problem:_
When looking up a password, the password is stored on the clipboard, and emptied after 15seconds.
This also overwrites/removes the content that was previously on the clipboard.

_Solution:_
In stead of clearing the clipboard, restore the data that was on the clipboard before the password lookup.

_Suggestion:_
the data shuld probably be passed on to `clear_clipboard.py`

**Comment by rcsmith533** [comment]
I'd like to work on this please!
