### ISSUE TITLE
Generate master key

### ISSUE THREAD

**Issue by Alex-CodeLab** [Alex-CodeLab/passwordmanager#2]
Problem:
Currently the `masterkey` is a hardcoded 32character string, and the user has to manually modify it.
There are many ways a user could make a mistake with this.  

Solution:
It would be better to automatically generate a key and write it to a file (if it doesn't exist already).

allowed characters: 
        string.ascii_letters + string.digits

**Comment by Buster28** [comment]
@Alex-CodeLab  I would like to pick this .

**Comment by Alex-CodeLab** [comment]
@kejriwalayushi28 
please go ahead. 
Any decent looking code gets merged.
