### ISSUE TITLE
Define db file

### ISSUE THREAD

**Issue by Alex-CodeLab** [Alex-CodeLab/passwordmanager#4]
Problem:
Having a hardcoded filename for the password DB makes it difficult to test, because the tests should use a temporary db file.

Solution:
Add a function to define the db filename , with argument  `--db-file`

**Comment by manojn29** [comment]
What I understood about this issue is that when you pass '--db-file' as an argument when executing the file along with the file name, the database that gets created should be named after that file name that's been passed. Or else it should be named as 'db.txt'. Am I right?

**Comment by Alex-CodeLab** [comment]
@manojn29 
yes, currently the database file is `db.txt`, but it would be nice to define a different file if needed. 
For most situations this is not needed, but when I tried I tried to make some test-cases I ran into the issue of overwriting the actual file (instead of using some temporary file, for example  `--db-file   custom_test_db.txt` ).

However... I just pushed some code for this, and I think it is working already.

**Comment by Niraj-Kamdar** [comment]
Why aren't you using actual database like sqlite3 database for this purpose.
It would be easy to do read-write-update operation on it.

**Comment by Alex-CodeLab** [comment]
@Niraj-Kamdar 
that is true, but it would also require a extra dependency, and make it (a little bit) more complex.
I'm guessing there would never be hundreds (or millions) of rows for such a application, so it does not really matter in terms of speed.

Other reason is to encrypt the content of the db/file. 

(I'm open to all kinds of ideas, but the long term goal is port it to some hardware device, so I would like to keep the size and dependencies as little as possible.)

**Comment by Alex-CodeLab** [comment]
plan has changed 
Will use Keyring instead to store/retrieve login/passwords
